/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch design system tokens
        'secondary-container': '#6001d1',
        'surface-container':   '#1d1f27',
        'error-container':     '#93000a',
        'on-background':       '#e1e2ed',
        'error':               '#ffb4ab',
        'on-surface':          '#e1e2ed',
        'outline-variant':     '#434655',
        'secondary':           '#d2bbff',
        'surface-container-high':    '#282a32',
        'surface-tint':        '#b4c5ff',
        'tertiary-fixed-dim':  '#ffb596',
        'surface-bright':      '#373942',
        'primary-container':   '#2563eb',
        'inverse-surface':     '#e1e2ed',
        'outline':             '#8d90a0',
        'inverse-primary':     '#0053db',
        'tertiary-container':  '#bc4800',
        'on-tertiary':         '#581e00',
        'on-secondary':        '#3f008e',
        'tertiary':            '#ffb596',
        'on-primary-container':'#eeefff',
        'surface':             '#11131b',
        'on-primary':          '#002a78',
        'on-tertiary-container':'#ffede6',
        'on-secondary-container': '#c9aeff',
        'surface-variant':     '#32343d',
        'primary-fixed-dim':   '#b4c5ff',
        'primary':             '#b4c5ff',
        'inverse-on-surface':  '#2e3039',
        'on-surface-variant':  '#c3c6d7',
        'primary-fixed':       '#dbe1ff',
        'on-primary-fixed':    '#00174b',
        'secondary-fixed':     '#eaddff',
        'surface-dim':         '#11131b',
        'on-primary-fixed-variant': '#003ea8',
        'surface-container-highest': '#32343d',
        'surface-container-low':     '#191b23',
        'surface-container-lowest':  '#0c0e16',
        'background':          '#11131b',
      },
      fontFamily: {
        'syne':        ['Syne', 'sans-serif'],
        'dm':          ['DM Sans', 'sans-serif'],
        'grotesk':     ['Space Grotesk', 'monospace'],
        // keep defaults for Tailwind utilities
        sans:          ['DM Sans', 'system-ui', 'sans-serif'],
        mono:          ['Space Grotesk', 'monospace'],
      },
      spacing: {
        gutter: '24px',
        margin: '48px',
      },
      animation: {
        'pulse-slow':  'pulse 3s cubic-bezier(0.4,0,0.6,1) infinite',
        'spin-slow':   'spin 3s linear infinite',
        'float':       'float 6s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%':      { transform: 'translateY(-20px)' },
        },
      },
    },
  },
  plugins: [],
};
